name: Setup Elasticsearch Cluster on Elastic Cloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-elasticsearch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Elasticsearch deployment
      env:
        ELASTIC_CLOUD_API_KEY: ${{ secrets.ELASTIC_CLOUD_API_KEY }}
      run: |
        python create_deployment.py

    - name: Wait for Elasticsearch to be ready
      env:
        ELASTIC_CLOUD_API_KEY: ${{ secrets.ELASTIC_CLOUD_API_KEY }}
      run: |
        python wait_for_deployment.py

    - name: Run Python tests
      env:
        ELASTIC_CLOUD_API_KEY: ${{ secrets.ELASTIC_CLOUD_API_KEY }}
        ELASTIC_CLOUD_USERNAME: ${{ secrets.ELASTIC_CLOUD_USERNAME }}
        ELASTIC_CLOUD_PASSWORD: ${{ secrets.ELASTIC_CLOUD_PASSWORD }}
      run: |
        pytest
